NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/mnasnet_b1_0_5_zcls_imagenet_224'
DATASET:
  NAME: 'ImageNet'
  TEST_ROOT: './data/imagenet'
  TOP_K: (1, 5)
TRANSFORM:
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor', 'Normalize')
  TEST_RESIZE: (224, )
  TEST_CROP: (224, 224)
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
DATALOADER:
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
MODEL:
  CONV:
    TYPE: 'Conv2d'
  NORM:
    TYPE: 'BatchNorm2d'
    SYNC_BN: False
    FIX_BN: False
    PARTIAL_BN: False
  ACT:
    TYPE: 'ReLU'
  COMPRESSION:
    WIDTH_MULTIPLIER: 0.5
    ROUND_NEAREST: 8
  BACKBONE:
    NAME: 'MNASNet'
    ARCH: 'mnasnet_b1'
    IN_PLANES: 3
  HEAD:
    NAME: 'GeneralHead2D'
    FEATURE_DIMS: 1280
    DROPOUT_RATE: 0.2
    NUM_CLASSES: 1000
  RECOGNIZER:
    NAME: 'MNASNet'
    PRELOADED: "outputs/converters/mnasnet0_5_imagenet.pth"
    PRETRAINED_NUM_CLASSES: 1000