NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/repvgg_a1_train_zcls_imagenet_224'
DATASET:
  NAME: 'ImageNet'
  TEST_ROOT: './data/imagenet'
  TOP_K: (1, 5)
TRANSFORM:
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor', 'Normalize')
  TEST_RESIZE: (224, )
  TEST_CROP: (224, 224)
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
DATALOADER:
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
MODEL:
  CONV:
    TYPE: 'Conv2d'
    ADD_BLOCKS: ("RepVGGBlock",)
  ACT:
    TYPE: 'ReLU'
  BACKBONE:
    NAME: 'RepVGG'
    ARCH: 'repvgg_a1'
    IN_PLANES: 3
    BASE_PLANES: 64
    LAYER_PLANES: (64, 128, 256, 512)
    DOWNSAMPLES: (1, 1, 1, 1)
  HEAD:
    NAME: 'GeneralHead2D'
    FEATURE_DIMS: 1280
    DROPOUT_RATE: 0.
    NUM_CLASSES: 1000
  RECOGNIZER:
    NAME: 'RepVGG'
    PRELOADED: "outputs/converters/repvgg_a1_train_imagenet.pth"
    PRETRAINED_NUM_CLASSES: 1000
    ZERO_INIT_RESIDUAL: True