NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/r152_torchvision_imagenet_224'
DATASET:
  NAME: 'ImageNet'
  TEST_ROOT: './data/imagenet'
  TOP_K: (1, 5)
TRANSFORM:
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor', 'Normalize')
  TEST_RESIZE: (224, )
  TEST_CROP: (224, 224)
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
DATALOADER:
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
MODEL:
  NORM:
    FIX_BN: False
    PARTIAL_BN: False
  BACKBONE:
    ARCH: 'resnet152'
  HEAD:
    NUM_CLASSES: 1000
  RECOGNIZER:
    NAME: 'TorchvisionResNet'
    TORCHVISION_PRETRAINED: True
    PRETRAINED_NUM_CLASSES: 1000
    ZERO_INIT_RESIDUAL: True