NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/rxt101_32x8d_torchvision_imagenet_224'
DATASET:
  NAME: 'ImageNet'
  TEST_ROOT: './data/imagenet'
  TOP_K: (1, 5)
  KEEP_RGB: True
TRANSFORM:
  TEST_METHODS: ('Resize', 'CenterCrop', 'Normalize', 'ToTensor')
  TEST_RESIZE: ((224, ), 1, 0, 1.0)
  TEST_CENTER_CROP: ((224, 224), 1.0)
  NORMALIZE: ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225), 255.0, 1.0)
  TO_TENSOR: 1.0
DATALOADER:
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
MODEL:
  NORM:
    FIX_BN: False
    PARTIAL_BN: False
  BACKBONE:
    ARCH: 'resnext101_32x8d'
  HEAD:
    NUM_CLASSES: 1000
  RECOGNIZER:
    NAME: 'TorchvisionResNet'
    PRELOADED: ""
    PRETRAINED_LOCAL: ""
    PRETRAINED_REMOTE: True
    PRETRAINED_NUM_CLASSES: 1000
    ZERO_INIT_RESIDUAL: True