NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/mobilenet_v2_zcls_imagenet_224'
DATASET:
  NAME: 'ImageNet'
  TEST_ROOT: './data/imagenet'
  TOP_K: (1, 5)
TRANSFORM:
  TEST_METHODS: ('Resize', 'CenterCrop', 'Normalize', 'ToTensor')
  TEST_RESIZE: ((224, 224), 1, 1.0)
  TEST_CENTER_CROP: ((224, 224), 1.0)
  NORMALIZE: ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225), 255.0, 1.0)
  TO_TENSOR: 1.0
DATALOADER:
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
MODEL:
  CONV:
    TYPE: 'Conv2d'
  NORM:
    TYPE: 'BatchNorm2d'
    SYNC_BN: False
    FIX_BN: False
    PARTIAL_BN: False
  ACT:
    TYPE: 'ReLU6'
  COMPRESSION:
    WIDTH_MULTIPLIER: 1.0
    ROUND_NEAREST: 8
  BACKBONE:
    NAME: 'MobileNetV2'
    IN_PLANES: 3
    BASE_PLANES: 32
  HEAD:
    NAME: 'GeneralHead2D'
    FEATURE_DIMS: 1280
    DROPOUT_RATE: 0.2
    NUM_CLASSES: 1000
  RECOGNIZER:
    NAME: 'MobileNetV2'
    PRELOADED: "outputs/converters/mobilenet_v2_imagenet.pth"
    PRETRAINED_NUM_CLASSES: 1000