NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/imagenet/mbv3_large_se_hsigmoid_imagenet_224_sgd_mslr_e100_g1'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 1
  EVAL_EPOCH: 1
  RESUME: False
  USE_TENSORBOARD: True
  HYBRID_PRECISION: True
DATASET:
  NAME: 'ImageNet'
  TRAIN_ROOT: './data/imagenet'
  TEST_ROOT: './data/imagenet'
  TOP_K: (1, 5)
TRANSFORM:
  TRAIN_METHODS: ('Resize', 'RandomCrop', 'RandomHorizontalFlip', 'ColorJitter', 'AUTO_AUGMENT', 'ToTensor', 'Normalize')
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor', 'Normalize')
  TRAIN_RESIZE: (224, )
  TEST_RESIZE: (224, )
  TRAIN_CROP: (224, 224)
  TEST_CROP: (224, 224)
  ColorJitter: (0.1, 0.1, 0.1, 0.1)
  AUGMENT_POLICY: "imagenet"
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 2
  PREFETCHER: True
MODEL:
  CONV:
    TYPE: 'Conv2d'
  NORM:
    TYPE: 'BatchNorm2d'
    SYNC_BN: False
    FIX_BN: False
    PARTIAL_BN: False
  ACT:
    TYPE: 'HSwish'
    SIGMOID_TYPE: 'HSigmoid'
  COMPRESSION:
    WIDTH_MULTIPLIER: 1.0
    ROUND_NEAREST: 8
  ATTENTION:
    WITH_ATTENTION: True
    REDUCTION: 4
    ATTENTION_TYPE: 'SqueezeAndExcitationBlock2D'
  BACKBONE:
    NAME: 'MobileNetV3'
    ARCH: 'mobilenetv3-large'
    IN_PLANES: 3
  HEAD:
    NAME: 'MobileNetV3'
    FEATURE_DIMS: 960
    INNER_DIMS: 1280
    NUM_CLASSES: 1000
  RECOGNIZER:
    NAME: 'MobileNetV3'
    PRELOADED: ""
    PRETRAINED: ""
    PRETRAINED_NUM_CLASSES: 1000
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 0.0125
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 1e-5
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 40, 70 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0