NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/reparam/acb_repvgg_b2g4_cifar100_224_e100_sgd_calr'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 5
  EVAL_EPOCH: 5
  RESUME: False
  USE_TENSORBOARD: True
  HYBRID_PRECISION: True
DATASET:
  NAME: 'CIFAR100'
  TRAIN_ROOT: './data/cifar'
  TEST_ROOT: './data/cifar'
  TOP_K: (1, 5)
TRANSFORM:
  TRAIN_METHODS: ('Resize', 'RandomCrop', 'RandomHorizontalFlip', 'AUTO_AUGMENT', 'ToTensor', 'Normalize')
  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor', 'Normalize')
  TRAIN_RESIZE: (256, )
  TEST_RESIZE: (224, )
  TRAIN_CROP: (224, 224)
  TEST_CROP: (224, 224)
  AUGMENT_POLICY: "imagenet"
  MEAN: (0.45, 0.45, 0.45)
  STD: (0.225, 0.225, 0.225)
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
  PREFETCHER: True
MODEL:
  CONV:
    TYPE: 'Conv2d'
    ADD_BLOCKS: ("ACBlock", "RepVGGBlock")
  ACT:
    TYPE: 'ReLU'
  BACKBONE:
    NAME: 'RepVGG'
    ARCH: 'repvgg_b2g4'
    IN_PLANES: 3
    BASE_PLANES: 64
    LAYER_PLANES: (64, 128, 256, 512)
    DOWNSAMPLES: (1, 1, 1, 1)
  HEAD:
    NAME: 'GeneralHead2D'
    FEATURE_DIMS: 2560
    DROPOUT_RATE: 0.
    NUM_CLASSES: 100
  RECOGNIZER:
    NAME: 'RepVGG'
    PRELOADED: ""
    PRETRAINED: ""
    PRETRAINED_NUM_CLASSES: 1000
    ZERO_INIT_RESIDUAL: True
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 0.0125
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 5e-4
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'CosineAnnearlingLR'
  IS_WARMUP: True
  GAMMA: 0.1
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 1e-5
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0